#include<linux/kernel.h>
#include<linux/init.h>
#include<linux/module.h>
#include<linux/hid.h>
#include<linux/usb.h>

#include "mouse_drv.h"
#include "set_led.h"
#define DEBUG
/**
 * feature report contains 90 bytes
 * the 2nd last byte is the checksum, generated by XORing all the bytes start from byte2 to byte87 
 */
static unsigned char calculate_checksum(struct razer_report *report)
{
    unsigned char checksum = 0;
    unsigned char *_report = (unsigned char*)report;
    
    unsigned int i;
    for(i = 2; i < 88; i++) {
        checksum ^= _report[i];
    }

    return checksum;
}

/**
 * Send USB set report by control pipe
 */
static int __must_check send_control_msg(struct usb_device *usb_dev, void const *data)
{    
    uint bmRequestype =  0x21;              // => host to device interface
    uint bRequest = HID_REQ_SET_REPORT;     // 0x09 set report request
    uint wValue = 0x0300;                   // Feature report
    uint wIndex = 0;                        // to interface 0
    uint wLength = RAZER_FEATURE_REPORT_LEN;// 0x5A
    char *buf;
    int len;

    /* kmalloc and copy data to new space */
    buf = kmemdup(data, wLength, GFP_KERNEL);
    if (buf == NULL)
        return -ENOMEM;

    /**
     * Send usb control message to endpoint0
     * note usb_control_msg can't be used within interrupt context(including bottom half) => use usb_submit_urb instead
     * return : negative error num if failed, else the number of bytes 
     */
    len = usb_control_msg(usb_dev, usb_sndctrlpipe(usb_dev, 0),
                          bRequest,      
                          bmRequestype, 
                          wValue,        
                          wIndex,       
                          buf,          
                          wLength,      
                          USB_CTRL_SET_TIMEOUT);

    // Wait
    usleep_range(600, 800);


    kfree(buf);

    return ((len < 0) ? len : ((len != wLength) ? -EIO : 0));
}

/**
 * Function to send request to device
 */
static int send_payload(struct razer_mouse_device *device, struct razer_report *request)
{
    int err=0;

    request->checksum = calculate_checksum(request);

    // send requests, one at a time
    mutex_lock(&device->lock);
    err = send_control_msg(device->usb_dev, request);
    mutex_unlock(&device->lock);

    if (err){
        printk(KERN_ERR"send control msg failed");
        return err;
    }

    return 0;
}

/**
 * Get an initialised razer report
 * Note: 
 *      Start | ID | Reserved | Num Params | Command | Sub Cmd | Params                       | Effect
 *      00      1f   000000     09           0f        02        01 LED_ID 02 01 00 01 r g b    breath 
 *      00      1f   000000     03           0f        04        01 LED_ID brightness           brightness adjustment
 *      00      1f   000000     03           0f        04        01 00 brightness               brightness adjustment for both(LED_ID==0x00)
 *      00      1f   000000     0b           0f        03        00 00 00 00 01 r g b r1 g1 b1  static color for both
 */
static struct razer_report get_razer_report(unsigned char arg_num, unsigned char command_class, unsigned char command_id)
{
    struct razer_report new_report = {0};

    new_report.start = 0x00; // pc to device
    new_report.transaction_id.id = 0x1f;
    new_report.arguments_num = arg_num;
    new_report.command_class = command_class;
    new_report.command_id.id = command_id;
    
    return new_report;
}
/* use echo -e -n '\xff\x00\xff' to input */
ssize_t attr_write_breath_effect_common(struct device *dev, struct device_attribute *attr, const char *buf, size_t count, unsigned char led_id)
{
    struct razer_mouse_device *device = dev_get_drvdata(dev);
    struct razer_report request = {0};
    struct rgb *color = NULL;   

    #ifdef DEBUG
    printk(KERN_INFO "count == %lu\n", count);
    #endif
    
    switch (count)
    {
    case 3:
        // single color mode
        request = get_razer_report(0x09, 0x0F, 0x02);
        color = (struct rgb*)&buf[0];
        #ifdef DEBUG
        printk(KERN_INFO "color->r: %0x, color->g: %0x, color->b: %0x\n", color->r, color->g, color->b);
        #endif
        request.arguments[0] = 0x01;        // save this setting
        request.arguments[1] = led_id;  
        request.arguments[2] = 0x02;        // Effect ID
        //request.arguments[3] = 0x01;      // tested, this can be either 0x00 or 0x01
        request.arguments[5] = 0x01;
        request.arguments[6] = color->r;
        request.arguments[7] = color->g;
        request.arguments[8] = color->b;
        
        break;
    
    default:
        // do nothing
        return count;
    }

    send_payload(device, &request);

    return count;
}

/* use echo -n 'num' to input, type cast to unsigned char -> 0<=num<=255 */
ssize_t attr_write_brightness_common(struct device *dev, struct device_attribute *attr, const char *buf, size_t count, unsigned char led_id)
{
    struct razer_mouse_device *device = dev_get_drvdata(dev);
    unsigned char brightness = (unsigned char)simple_strtoul(buf, NULL, 0); // base = 0 -> auto detect hex or dec..., hex start with 0x
    struct razer_report request = {0};

    #ifdef DEBUG
    printk(KERN_INFO"brightness = %u\n",(unsigned int)brightness);
    #endif

    request = get_razer_report(0x03, 0x0F, 0x04);
    request.arguments[0] = 0x01;     // save this setting
    request.arguments[1] = led_id;
    request.arguments[2] = brightness;

    send_payload(device, &request);

    return count;
}

/**
 * Test any "Set Report" here
 * current setting:       
 *      input 1 byte => set brightness for both led
 *      input 3 byte => assume each byte represents rgb respectively set color for both led
 *      use echo -e -n '\xff' or '\xff\x00\xff' to input, for example
 */
ssize_t attr_write_test_common(struct device *dev, struct device_attribute *attr, const char *buf, size_t count, unsigned char led_id){
    struct razer_mouse_device *device = dev_get_drvdata(dev);
    struct razer_report request = {0};

    struct rgb* color= NULL;
    unsigned char brightness = 0x00;
    switch (count)
    {
    case 1: 
        // set both logo and scroll wheel brightness
        brightness = *(unsigned char*)buf;
        #ifdef DEBUG
        printk(KERN_INFO "brightness: %u",(unsigned int)brightness);
        #endif
        request = get_razer_report(0x03, 0x0f, 0x04);
        request.arguments[0] = 0x01;
        request.arguments[2] = brightness;
        break;
    case 3:
        // set both logo and scroll wheel color
        color = (struct rgb*)buf;
        #ifdef DEBUG
        printk(KERN_INFO "color->r: %0x, color->g: %0x, color->b: %0x\n",color->r,color->g,color->b);
        #endif
        request = get_razer_report(0x0b, 0x0f, 0x03);
        request.arguments[4] = 0x01;

        request.arguments[8] = request.arguments[5] = color->r;
        request.arguments[9] = request.arguments[6] = color->g;
        request.arguments[10] = request.arguments[7] = color->b;
        break;
    default:
        return count; // do nothing
    }

    send_payload(device,&request);

    return count;
}
